# ==============================================================================
# Figure: [FIGURE_NAME]
# Description: [Brief description of what this figure shows]
#
# IMPORTANT: This template enforces anti-hardcoding rules (CRITICAL-FAILURE-004)
# - NO hardcoded hex colors (use color_defs)
# - NO ggsave() (use save_publication_figure)
# - NO custom theme definitions (use theme_foundation_plr)
# - NO hardcoded dimensions (load from config)
#
# See: .claude/docs/meta-learnings/CRITICAL-FAILURE-004-r-figure-hardcoding.md
# ==============================================================================

# ==============================================================================
# MANDATORY HEADER - DO NOT REMOVE OR MODIFY
# ==============================================================================

# Find project root (required for all paths)
PROJECT_ROOT <- (function() {
  d <- getwd()
  while (d != dirname(d)) {
    if (file.exists(file.path(d, "CLAUDE.md"))) return(d)
    d <- dirname(d)
  }
  stop("Could not find project root (no CLAUDE.md found)")
})()

# Load figure system (MANDATORY)
source(file.path(PROJECT_ROOT, "src/r/figure_system/config_loader.R"))
source(file.path(PROJECT_ROOT, "src/r/figure_system/save_figure.R"))
source(file.path(PROJECT_ROOT, "src/r/theme_foundation_plr.R"))

# Load colors from YAML (MANDATORY - no hardcoded colors!)
color_defs <- load_color_definitions()

# Load figure configuration (for dimensions, etc.)
# fig_config <- load_figure_config("fig_name")

# ==============================================================================
# END MANDATORY HEADER
# ==============================================================================

# Required packages
library(ggplot2)
library(dplyr)

# ==============================================================================
# DATA LOADING
# ==============================================================================

# Load data from JSON (generated by Python extraction)
# data_path <- file.path(PROJECT_ROOT, "figures/generated/data/fig_xxx.json")
# data <- jsonlite::fromJSON(data_path)

# ==============================================================================
# PLOTTING
# ==============================================================================

# Example using color_defs (CORRECT):
# ggplot(data, aes(x = x, y = y)) +
#   geom_line(color = color_defs[["--color-primary"]], linewidth = 0.8) +
#   geom_point(fill = color_defs[["--color-fm-primary"]], shape = 21) +
#   theme_foundation_plr()

# WRONG - DO NOT DO THIS:
# geom_line(color = "#006BA2")  # BANNED - hardcoded hex
# ggsave("output.png", p)        # BANNED - use save_publication_figure

# ==============================================================================
# SAVE FIGURE
# ==============================================================================

# Use the figure system (loads dimensions from config)
# save_publication_figure(p, "fig_name")

# If you need custom dimensions (rare), load from config:
# save_publication_figure(p, "fig_name",
#   width = fig_config$dimensions$width,
#   height = fig_config$dimensions$height
# )

cat("✅ Figure generated successfully\n")
