# Featurization Comparison
# Shows the 9pp gap: handcrafted (0.83) vs embeddings (0.74)
# Task 2.7 from ggplot2-viz-remaining-plan.xml
#
# Created: 2026-01-25
# Author: Foundation PLR Team

# ==============================================================================
# SETUP
# ==============================================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(jsonlite)  # For loading provenance-tracked data
})

# Determine project root
find_project_root <- function() {
  markers <- c("pyproject.toml", "CLAUDE.md", ".git")
  dir <- getwd()
  while (dir != dirname(dir)) {
    if (any(file.exists(file.path(dir, markers)))) {
      return(dir)
    }
    dir <- dirname(dir)
  }
  stop("Could not find project root")
}

PROJECT_ROOT <- find_project_root()

# Source figure system (MANDATORY)
source(file.path(PROJECT_ROOT, "src/r/figure_system/config_loader.R"))
source(file.path(PROJECT_ROOT, "src/r/figure_system/save_figure.R"))
source(file.path(PROJECT_ROOT, "src/r/theme_foundation_plr.R"))
source(file.path(PROJECT_ROOT, "src/r/color_palettes.R"))

# Load color definitions from YAML
color_defs <- load_color_definitions()

# ==============================================================================
# DATA (loaded from JSON with provenance)
# ==============================================================================

# Load data from JSON (generated by scripts/export_featurization_comparison.py)
json_path <- file.path(PROJECT_ROOT, "data", "r_data", "featurization_comparison.json")
if (!file.exists(json_path)) {
  stop("ERROR: featurization_comparison.json not found!\n",
       "Run: python scripts/export_featurization_comparison.py")
}

json_data <- jsonlite::fromJSON(json_path)

# Validate provenance
message(sprintf("Data source: %s (hash: %s)",
                json_data$metadata$data_source$database,
                json_data$metadata$data_source$db_hash))

# Build data frame from JSON
# Note: jsonlite returns data frames for arrays of objects, not lists
methods_df <- json_data$methods
featurization_data <- data.frame(
  method = methods_df$display_name,
  auroc = methods_df$auroc,
  auroc_ci_lo = methods_df$auroc_ci_lo,
  auroc_ci_hi = methods_df$auroc_ci_hi,
  category = c("Proposed", "Alternative"),
  stringsAsFactors = FALSE
) %>%
  mutate(
    method = factor(method, levels = rev(method)),  # Reverse for horizontal bars
    label = sprintf("%.3f", auroc)
  )

# Gap from JSON (verified)
gap <- json_data$gap_pp / 100  # Convert from pp to decimal

message(sprintf("AUROC gap: %.1f percentage points", gap * 100))

# ==============================================================================
# COMPARISON PLOT
# ==============================================================================

p_feature <- ggplot(featurization_data, aes(x = auroc, y = method, fill = category))
p_feature <- gg_add(p_feature,
  # Reference lines for context
  geom_vline(xintercept = c(0.7, 0.8, 0.9), linetype = "dotted", color = color_defs[["--color-border"]], linewidth = 0.3),
  # Error bars
  geom_errorbarh(aes(xmin = auroc_ci_lo, xmax = auroc_ci_hi), height = 0.2, color = color_defs[["--color-text-primary"]]),
  # Bars
  geom_col(width = 0.6, alpha = 0.9),
  # Value labels
  geom_text(aes(label = label, x = auroc + 0.01), hjust = 0, size = 5, fontface = "bold"),
  # Gap annotation
  annotate(
    "segment",
    x = featurization_data$auroc[2], xend = featurization_data$auroc[1],
    y = 1.5, yend = 1.5,
    arrow = arrow(ends = "both", length = unit(0.1, "inches")),
    color = color_defs[["--color-negative"]],
    linewidth = 1
  ),
  annotate(
    "text",
    x = mean(featurization_data$auroc), y = 1.65,
    label = sprintf("+%.0f pp", gap * 100),
    color = color_defs[["--color-negative"]],
    size = 5,
    fontface = "bold"
  ),
  # Scales
  scale_fill_manual(values = c("Proposed" = color_defs[["--color-primary"]], "Alternative" = color_defs[["--color-annotation"]]), guide = "none"),
  scale_x_continuous(limits = c(0.65, 0.95), breaks = seq(0.65, 0.95, 0.05)),
  # Labels (academic mode - no title/subtitle/caption for journal submission)
  labs(
    x = "AUROC (CatBoost classifier)",
    y = NULL
  ),
  theme_foundation_plr(),
  theme(
    axis.text.y = element_text(size = 11, face = "bold")
  )
)

# Save using figure system (formats from YAML config)
# Dimensions loaded from configs/VISUALIZATION/figure_registry.yaml
save_publication_figure(p_feature, "fig_featurization_comparison")

# ==============================================================================
# SUMMARY
# ==============================================================================

message("\n========================================")
message("Featurization Comparison Complete")
message("========================================")
message("Key finding:")
message(sprintf("  Handcrafted features: AUROC = %.3f", featurization_data$auroc[1]))
message(sprintf("  FM embeddings: AUROC = %.3f", featurization_data$auroc[2]))
message(sprintf("  Gap: +%.0f pp in favor of handcrafted", gap * 100))
