"""Utility modules for Foundation PLR."""

from .paths import (
    PROJECT_ROOT,
    clear_path_caches,
    get_classification_experiment_id,
    get_config_dir,
    get_figures_output_dir,
    get_json_data_dir,
    get_mlflow_registry_dir,
    get_mlruns_dir,
    get_preprocessed_signals_db_path,
    get_results_db_path,
    get_seri_db_path,
    get_visualization_config_dir,
    resolve_path,
)

# Data mode detection and isolation
from .data_mode import (
    SYNTHETIC_ENV_VAR,
    SYNTHETIC_EXPERIMENT_PREFIX,
    SYNTHETIC_RUN_PREFIX,
    SyntheticDataError,
    add_synthetic_prefix_to_run_name,
    get_data_mode,
    get_figures_dir_for_mode,
    get_mlflow_tags_for_mode,
    get_production_mlflow_tags,
    get_results_db_path_for_mode,
    get_synthetic_figures_dir,
    get_synthetic_mlflow_tags,
    get_synthetic_output_dir,
    is_synthetic_experiment_name,
    is_synthetic_from_config,
    is_synthetic_from_filename,
    is_synthetic_mode,
    is_synthetic_run_name,
    remove_synthetic_prefix_from_run_name,
    validate_not_synthetic,
    validate_run_for_production_extraction,
)

# Re-export legacy utility functions for backward compatibility
from ._legacy import (
    check_for_device,
    check_timegpt_token,
    get_artifacts_dir,
    get_data_dir,
    get_repo_root,
    get_time_hash,
    get_time_vector,
    pandas_col_condition_filter,
    pandas_concat,
)

__all__ = [
    # Path utilities (new)
    "PROJECT_ROOT",
    "get_mlruns_dir",
    "get_classification_experiment_id",
    "get_seri_db_path",
    "get_results_db_path",
    "get_preprocessed_signals_db_path",
    "get_figures_output_dir",
    "get_json_data_dir",
    "get_config_dir",
    "get_visualization_config_dir",
    "get_mlflow_registry_dir",
    "resolve_path",
    "clear_path_caches",
    # Data mode detection and isolation
    "SYNTHETIC_RUN_PREFIX",
    "SYNTHETIC_EXPERIMENT_PREFIX",
    "SYNTHETIC_ENV_VAR",
    "SyntheticDataError",
    "is_synthetic_mode",
    "is_synthetic_from_config",
    "is_synthetic_from_filename",
    "get_data_mode",
    "add_synthetic_prefix_to_run_name",
    "remove_synthetic_prefix_from_run_name",
    "is_synthetic_run_name",
    "is_synthetic_experiment_name",
    "get_synthetic_output_dir",
    "get_synthetic_figures_dir",
    "get_results_db_path_for_mode",
    "get_figures_dir_for_mode",
    "get_synthetic_mlflow_tags",
    "get_production_mlflow_tags",
    "get_mlflow_tags_for_mode",
    "validate_not_synthetic",
    "validate_run_for_production_extraction",
    # Legacy utilities (for backward compatibility)
    "get_repo_root",
    "get_data_dir",
    "get_artifacts_dir",
    "get_time_vector",
    "check_timegpt_token",
    "get_time_hash",
    "pandas_concat",
    "pandas_col_condition_filter",
    "check_for_device",
]
